# Generated by Django 5.2.6 on 2025-10-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_callwaiter_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callwaiter',
            name='seen',
        ),
    ]
